
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-west-2
  version: "1.21"

iam:
  serviceRoleARN: arn:aws:iam::123456789012:role/EKSClusterRole

nodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 4

