#original
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties: {}     
    #with no properties use the {} open close braces


Lecture 12:
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # AccessControl: PublicRead / this does not work any longer, so delete this line
      BucketName: "insert-some-random-string-here"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
          
          
OR...

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred




#Resources:
#  MyS3Bucket:
#    Type: AWS::S3::Bucket
#    Properties:   #with properties remove the {}
#        BucketName: #some.where.in.middle.earth.by.the.shire  #with bucket name
  

#Resources:
#  MyS3Bucket:
#    Type: AWS::S3::Bucket
#    DeletionPolicy: Retain
#    UpdateReplacePolicy: Retain
#    Properties: {}



#cloudFormation commandline aws cloudformation deploy --template-file short.yaml --stack-name absolutely-crazy-stackname
# or Create stack with new resources. upload template-file
#
#Resources:
#  MyS3BucketAABBCC:  { logical ID }
#    Type: AWS::S3::Bucket
#    DeletionPolicy: Retain
#    UpdateReplacePolicy: Retain
#    Properties: {}
#    
