AWSTemplateFormatVersion: '2010-09-09'
Description: Create a simple EC2 instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ad
      InstanceType: t2.medium
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - sg-0e11
          SubnetId: subnet-0411
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 60
            VolumeType: gp3

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:sts::${AWS::AccountId}:assumed-role/blahblah-user/dishrag
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref AmazonEC2ReadOnlyAccess

  AmazonEC2ReadOnlyAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:Describe*
            Resource: '*'




Use parameters statements and !refsgenerate a minimal usable cloudformation yaml for a simple ec2 with the following data: ami-0ad, instance type t2.med, owner arn:aws:sts:xxxxx:assumed-role/blahblah-user/dishrag, EBS 60 gp3, eth0, subnet-041, security group id: sg-0e11, subnet: 0411, instance role profile: arn:aws:iam::53326 blablah , keypair: xlaxlax.  
